version: "3"

services:
  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp 
      - 443:443/tcp 
      - 443:443/udp 
      - 3000:3000/tcp

    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf

    networks:
      net:
        ipv4_address: 10.0.0.2

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29

